from datetime import datetime
from ..models.incident import Incident
# I auto-generate runbooks from resolved incidents
class RunbookGenerator:
    def generate(self, incident: Incident) -> str:
        return f"""# Runbook: {incident.type.value}
_ Auto-generated by Nexus on {datetime.utcnow().date()} – I learned from incident {incident.id[:8]}_

## Symptoms
- Target: `{incident.target_id}`
- Signal: `{incident.source_signal}`
- Severity: {incident.severity.value}

## Root Cause
{incident.root_cause or "Undetermined – see logs"}

## Diagnosis steps I performed
1. I collected observability signals via probes
2. I ran statistical anomaly detection (z-score)
3. I correlated with recent changes
4. Confidence: {incident.confidence:.0%}

## Remediation (auto-applied)
- Fix PR: {incident.fix_pr_url or "(manual)"}
- Summary: {incident.fix_summary or "See IaC diff in PR"}

## Verification
- MTTR: {incident.mttr_seconds}s
- Verified: {incident.verified}

## Prevention
- I recommend adding an alert at 70% of threshold
- I recommend reviewing capacity quarterly

---
*Generated by Nexus Learning Engine – I improve this runbook every time I see a similar incident.*
"""
