package config

import (
	"fmt"

	"github.com/spf13/viper"
)

// setDefaults registers default values so a minimal nexus.yaml still
// produces a fully populated Config.
func setDefaults(v *viper.Viper) {
	v.SetDefault("project.name", "nexus-project")
	v.SetDefault("project.environment", "dev")
	v.SetDefault("autonomy.level", 0)
	v.SetDefault("database.dsn", "")
	v.SetDefault("engine.cycle_interval", "5m")
	v.SetDefault("engine.http_port", 8080)
}

// DefaultYAML renders the starter configuration written by 'nexus init'.
// I keep it heavily commented because this file is the first thing a new
// user edits.
func DefaultYAML(projectName string) string {
	return fmt.Sprintf(`# Nexus configuration
# Generated by 'nexus init'. Environment variables with the NEXUS_ prefix
# override any value in this file (for example NEXUS_AUTONOMY_LEVEL=1).

project:
  name: %s
  environment: dev

autonomy:
  # 0 = observe only (recommended starting point)
  # 1 = recommend fixes via pull request
  # 2 = auto-apply low-risk fixes
  # 3 = auto-apply behind an OPA policy gate
  # 4 = full autonomy
  level: 0

database:
  # PostgreSQL connection string. Leave empty to run without persistence
  # (observation results are printed but not stored).
  # Example: postgres://nexus:secret@localhost:5432/nexus?sslmode=disable
  dsn: ""

engine:
  # How often the closed-loop cycle runs.
  cycle_interval: 5m
  # Port for the Nexus HTTP API.
  http_port: 8080

# Infrastructure targets that Nexus observes. Providers: kubernetes,
# aws, gcp, azure, localstack.
targets: []
#  - name: demo-k8s
#    provider: kubernetes
#    endpoint: https://127.0.0.1:6443
#  - name: demo-aws
#    provider: localstack
#    endpoint: http://localhost:4566
#    region: us-east-1
`, projectName)
}
